name: cobacoba

on:
  workflow_dispatch:
    
jobs:
  coba:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2   
    - name: Install packages
      run: |
        install.packages("e1071", dependencies = TRUE)
        install.packages("tidyverse", dependencies = TRUE)
        install.packages("caret")
      shell: Rscript {0} 
    - name: Coba
      run: Rscript coba.R
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Changed files
